tutorial_user:
    resource: "@TutorialUserBundle/Resources/config/routing.yml"
    prefix:   /

tutorial_blog:
    resource: "@TutorialBlogBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"